package com.aiadaptive.Controller;

import com.aiadaptive.domain.Recommendation;
import com.aiadaptive.services.RecommendationService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
    @RequestMapping("/api/recommendations")
    @Tag(name = "Recommendations", description = "Endpoints for managing personalized learning recommendations")
    public class RecommendationController {

    private final RecommendationService service;

    public RecommendationController(RecommendationService service) {
                this.service = service;
    }

    @Operation(
                summary = "Get all recommendations",
                description = "Retrieves a list of all personalized learning recommendations generated by the AI system"
            )
            @ApiResponses(value = {
                        @ApiResponse(
                                        responseCode = "200",
                                        description = "Successfully retrieved list of recommendations",
                                        content = @io.swagger.v3.oas.annotations.media.Content(
                                                            mediaType = "application/json",
                                                            array = @ArraySchema(schema = @Schema(implementation = Recommendation.class)))
                                    )
            })
            @GetMapping
            public List<Recommendation> getAll() {
                        return service.getAllRecommendations();
            }

    @Operation(
                summary = "Create a new recommendation",
                description = "Creates a new personalized learning recommendation for a student based on their learning profile"
            )
            @ApiResponses(value = {
                        @ApiResponse(
                                        responseCode = "200",
                                        description = "Recommendation successfully created",
                                        content = @io.swagger.v3.oas.annotations.media.Content(
                                                            mediaType = "application/json",
                                                            schema = @Schema(implementation = Recommendation.class))
                                    ),
                        @ApiResponse(
                                        responseCode = "400",
                                        description = "Invalid recommendation data provided",
                                        content = @io.swagger.v3.oas.annotations.media.Content
                                    )
            })
            @PostMapping
            public Recommendation create(
                        @Parameter(description = "Recommendation object to be created", required = true)
                        @RequestBody Recommendation rec) {
                        return service.createRecommendation(rec);
            }
    }
